### ISSUE TITLE
OTIO JSON adapter raises non-pythonic exception when file doesn't exist

### ISSUE THREAD

**Issue by reinecke** [AcademySoftwareFoundation/OpenTimelineIO#1307]
### Incorrect Functionality and General Questions

When using the OTIO JSON adapter to read a file that fails to open, the exception raised is inconsistent with Python and other adapters - `ValueError` is raised instead of `FileNotFoundError`.

## To Reproduce

1. Operating System: macOS 10.15.7
2. Python version: 3.9.7
3. Example snippet that demonstrates the issue: see below
4. OpenTimelineIO release version or commit hash: 0.14.1

```python
>>> timeline = otio.adapters.read_from_file("/tmp/doesnotexist.otio")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/ereinecke/envs/otio/lib/python3.9/site-packages/opentimelineio/adapters/__init__.py", line 143, in read_from_file
    return adapter.read_from_file(
  File "/Users/ereinecke/envs/otio/lib/python3.9/site-packages/opentimelineio/adapters/adapter.py", line 145, in read_from_file
    result = self._execute_function(
  File "/Users/ereinecke/envs/otio/lib/python3.9/site-packages/opentimelineio/plugins/python_plugin.py", line 174, in _execute_function
    return (getattr(self.module(), func_name)(**kwargs))
  File "/Users/ereinecke/envs/otio/lib/python3.9/site-packages/opentimelineio/adapters/otio_json.py", line 45, in read_from_file
    return core.deserialize_json_from_file(filepath)
ValueError: failed to open file for reading: /tmp/doesnotexist.otio
```

## Expected Behavior

Looking at Python's `open` function and other OTIO adapters (likely using Python's `open` under the hood), raising an exception of `FileNotFoundError` would be more correct.

Following are some examples of comparable tasks raising `FileNotFoundError`.

Python `open`:
```python
>>> f = open("/tmp/doesnotexist.otio")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/doesnotexist.otio'

OTIO EDL adapter:
```python
>>> timeline = otio.adapters.read_from_file("/tmp/doesnotexist.edl")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/ereinecke/envs/otio/lib/python3.9/site-packages/opentimelineio/adapters/__init__.py", line 143, in read_from_file
    return adapter.read_from_file(
  File "/Users/ereinecke/envs/otio/lib/python3.9/site-packages/opentimelineio/adapters/adapter.py", line 137, in read_from_file
    with open(filepath, 'r') as fo:
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/doesnotexist.edl'
```

OTIO FCP 7 XML Adapter:
```python
>>> timeline = otio.adapters.read_from_file("/tmp/doesnotexist.xml")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/ereinecke/envs/otio/lib/python3.9/site-packages/opentimelineio/adapters/__init__.py", line 143, in read_from_file
    return adapter.read_from_file(
  File "/Users/ereinecke/envs/otio/lib/python3.9/site-packages/opentimelineio/adapters/adapter.py", line 137, in read_from_file
    with open(filepath, 'r') as fo:
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/doesnotexist.xml'
```

## Additional Context

It may make sense to audit the behavior for other file IO exception cases (permissions errors in particular) to make sure it behaves properly.

**Comment by JeanChristopheMorinPerso** [comment]
@reinecke I created a pull request to address this: https://github.com/AcademySoftwareFoundation/OpenTimelineIO/pull/1313.
