### ISSUE TITLE
ImageSequenceReference' object has no attribute 'target_url'

### ISSUE THREAD

**Issue by woshimanong1990** [AcademySoftwareFoundation/OpenTimelineIO#1352]
## Bug Report

ImageSequenceReference' object has no attribute 'target_url'
`
    base, ext = os.path.splitext(os.path.basename(fname)) 

    ref = otio.schema.ImageSequenceReference(

        target_url_base=os.path.dirname(fname),

        # available range is the content available for editing

        available_range=available_range_from_list,

        start_frame=int(base.split(".")[-1]),

        frame_step=1,

        rate=25,

        name_prefix=base + ".",

        name_suffix=ext,

        frame_zero_padding=4,)
`

## To Reproduce

1. Operating System win10
2. Python version python3.6.8
3. Example snippet that demonstrates the issue - if it's a build issue,
4. OpenTimelineIO release version or commit hash  0.14.1 

## Logs

Traceback (most recent call last):
  File "check_adobe_pr/check_create_photo_clip.py", line 140, in <module>
    main()
  File "check_adobe_pr/check_create_photo_clip.py", line 136, in main
    otio.adapters.write_to_file(tl, "auto_create_photo.xml")
  File "opentimelineio\adapters\__init__.py", line 194, in write_to_file
    **adapter_argument_map
  File "opentimelineio\adapters\adapter.py", line 188, in write_to_file
    result = self.write_to_string(input_otio, **adapter_argument_map)
  File "opentimelineio\adapters\adapter.py", line 258, in write_to_string
    **adapter_argument_map
  File "opentimelineio\plugins\python_plugin.py", line 174, in _execute_function
    return (getattr(self.module(), func_name)(**kwargs))
  File "opentimelineio\adapters\fcp_xml.py", line 1968, in write_to_string
    input_otio, timeline_range, br_map
  File "opentimelineio\adapters\fcp_xml.py", line 1276, in wrapper
    elem = func(item, *args, **kwargs)
  File "opentimelineio\adapters\fcp_xml.py", line 1852, in _build_sequence_for_timeline
    timeline.tracks, sequence_e, timeline_range, br_map
  File "opentimelineio\adapters\fcp_xml.py", line 1905, in _add_stack_elements_to_sequence
    track_elements = _build_top_level_track(track, track_rate, br_map)
  File "opentimelineio\adapters\fcp_xml.py", line 1793, in _build_top_level_track
    _build_item(item, timeline_range, transition_offsets, br_map)
  File "opentimelineio\adapters\fcp_xml.py", line 1751, in _build_item
    br_map
  File "opentimelineio\adapters\fcp_xml.py", line 1276, in wrapper
    elem = func(item, *args, **kwargs)
  File "opentimelineio\adapters\fcp_xml.py", line 1622, in _build_clip_item
    clip_item_e.append(_build_file(clip_item.media_reference, br_map))
  File "opentimelineio\adapters\fcp_xml.py", line 1276, in wrapper
    elem = func(item, *args, **kwargs)
  File "opentimelineio\adapters\fcp_xml.py", line 1474, in _build_file
    url_path = _url_to_path(media_reference.target_url)
 AttributeError: 'opentimelineio._otio.ImageSequenceReference' object has no attribute 'target_url'

**Comment by reinecke** [comment]
Hi @woshimanong1990
I looks like you're trying to make an FCP 7 XML with image sequences. The FCP XML format doesn't have a way to specify an image sequence in it as a source for a clip that I know of so we haven't implemented support for `ImageSequenceReference` in the FCP 7 XML adapter (though we should, at least, make the error message nicer).

It looks like you're trying to load the Image Sequence in Premiere, how would you expect it to show up in the timeline? Do you have an example of an image sequence working in Premiere that you could export as FCP 7 XML? Ideally we'd be able to support this but the "correct" way to do it has been a bit unclear.

**Comment by reinecke** [comment]
I think this may be a duplicate of #1092, but I want to clarify I understand correctly before closing.

**Comment by reinecke** [comment]
Closing as a duplicate of #1092 for now - if I'm mistaken please let me know and I'll re-open.
