### ISSUE TITLE
`extract_adapters`: plugin docs generation fails when hook is present

### ISSUE THREAD

**Issue by timlehr** [AcademySoftwareFoundation/OpenTimelineIO#1643]
Before opening a bug report, please search open and closed issues to see if the problem has already been addressed. If there is such a report, and your issue is not adequately addressed there, please reference the issues in your new report.

## Bug Report

On the `extract_adapters` branch there is an issue with the plugin docs generation / tests. If there are hooks with hook scripts in the path, the code doesn't handle them correctly and we get an error:

```python
======================================================================
ERROR: test_plugin_documentation (test_serialized_schema.PluginDocumentationTester)
Verify that the plugin manifest matches what is checked into the
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/tlehr/dev/OpenTimelineIO/tests/test_serialized_schema.py", line 62, in test_plugin_documentation
    sanitized_paths=True
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/opentimelineio/console/autogen_plugin_documentation.py", line 337, in generate_and_write_documentation_plugins
    sanitized_paths
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/opentimelineio/console/autogen_plugin_documentation.py", line 283, in _manifest_formatted
    if manifest_paths and plug['from manifest'] not in manifest_paths:
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/opentimelineio/core/_core_utils.py", line 223, in __getitem__
    return self.__internal_getitem__(index)
TypeError: __internal_getitem__(): incompatible function arguments. The following argument types are supported:
    1. (self: opentimelineio._otio.AnyVector, index: int) -> object

Invoked with: ['studio_pre_write_hook'], 'from manifest'

----------------------------------------------------------------------
```

**Comment by apetrynet** [comment]
Fixed in PR #1644
