### ISSUE TITLE
IndexError: Signature "triggered()" not found for signal:

### ISSUE THREAD

**Issue by chlowden** [AcademySoftwareFoundation/OpenTimelineIO#1806]
# Required:
------------
[ x] I believe this isn't a duplicate topic  
[x ] This report is not related to an adapter  

For adapter related issues, please go to the appropriate repository - likely in
the [OpenTimelineIO github organization](https://github.com/OpenTimelineIO/).
For general questions and help please use the
[Academy Software Foundation slack](https://slack.aswf.io/),
[#opentimelineio](https://academysoftwarefdn.slack.com/messages/CMQ9J4BQC).

## Select One:

[ ] Build problem  
[x ] Incorrect Functionality or bug  
[ ] New feature or functionality  

## Description

Following an initial install on Rocky 8.10, then loading an otio file that imports fine in davinci resolve, I get the error below

otioview SolLevante_HDR10_r2020_ST2084_UHD_24fps_1000nit.otio 
Traceback (most recent call last):
  File "/home/admin/anaconda3/bin/otioview", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/admin/anaconda3/lib/python3.11/site-packages/opentimelineview/console.py", line 292, in main
    window = Main(
             ^^^^^
  File "/home/admin/anaconda3/lib/python3.11/site-packages/opentimelineview/console.py", line 153, in __init__
    self._create_navigation_menu(navigation_menu)
  File "/home/admin/anaconda3/lib/python3.11/site-packages/opentimelineview/console.py", line 222, in _create_navigation_menu
    navigation_menu.triggered[[QAction]].connect(__callback)
    ~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^
IndexError: Signature "triggered()" not found for signal: "triggered". Available candidates: "triggered(QAction*)"


# Optional
-----------

## Environment
Rocky 8.10
Operating System:  
Python version if appropriate:  
Python 3.11.7

## Reproduction Steps

## Log output if appropriate

## Sample data and other attachements

**Comment by reinecke** [comment]
Hi there, thanks for reporting the issue!

A lot of our attention has been on a replacement for otioview called [raven](https://github.com/OpenTimelineIO/raven) - is raven able to address your use case (you can download a pre-built version [here](https://github.com/OpenTimelineIO/raven/actions/runs/11110151506))?

**Comment by chlowden** [comment]
Thank you for the info. Do you know if there is a Rocky Linux friendly version?
