### ISSUE TITLE
AAF Writer: NoneType MediaReference causing errors on AAF Export

### ISSUE THREAD

**Issue by conorhodder** [AcademySoftwareFoundation/OpenTimelineIO#535]
I am reading in an AAF produced by Media Composer 2018.11, and attempting to write back out the exact timeline again. The media for the AAF is not accessible, but considering there is no required manipulation of this I was hoping that wouldn't be necessary.

`t = otio.adapters.read_from_file(aaf_path)
otio.adapters.write_to_file(t, out_path)`

TRACEBACK RESULTS:
`Traceback (most recent call last):
  File "~/read_aaf.py", line 26, in <module>
    main(aaf, out)
  File "~/read_aaf.py", line 17, in main
    otio.adapters.write_to_file(timeline, out)
  File "~\venv\lib\site-packages\opentimelineio\adapters\__init__.py", line 194, in write_to_file
    **adapter_argument_map
  File "~\venv\lib\site-packages\opentimelineio\adapters\adapter.py", line 188, in write_to_file
    **adapter_argument_map
  File "~\venv\lib\site-packages\opentimelineio\plugins\python_plugin.py", line 128, in _execute_function
    return (getattr(self.module(), func_name)(**kwargs))
  File "~\venv\lib\site-packages\opentimelineio_contrib\adapters\advanced_authoring_format.py", line 961, in write_to_file
    aaf_writer.validate_metadata(timeline)
  File "~\venv\lib\site-packages\opentimelineio_contrib\adapters\aaf_adapter\aaf_writer.py", line 173, in validate_metadata
    sum([check.errors for check in all_checks], [])))
opentimelineio_contrib.adapters.aaf_adapter.aaf_writer.AAFValidationError: 
05B-407-04A.new.03<class 'opentimelineio.schema.clip.Clip'> Clip.media_reference.available_range.duration.rate does not exist, 'NoneType' object has no attribute 'duration'
05B-407-04A.new.03<class 'opentimelineio.schema.clip.Clip'> Clip.media_reference.available_range.start_time.rate does not exist, 'NoneType' object has no attribute 'start_time'
05B-406-01B.new.03<class 'opentimelineio.schema.clip.Clip'> Clip.media_reference.available_range.duration.rate does not exist, 'NoneType' object has no attribute 'duration'
05B-406-01B.new.03<class 'opentimelineio.schema.clip.Clip'> Clip.media_reference.available_range.start_time.rate does not exist, 'NoneType' object has no attribute 'start_time'
37/2.new.01<class 'opentimelineio.schema.clip.Clip'> Clip.media_reference.available_range.duration.rate does not exist, 'NoneType' object has no attribute 'duration'
37/2.new.01<class 'opentimelineio.schema.clip.Clip'> Clip.media_reference.available_range.start_time.rate does not exist, 'NoneType' object has no attribute 'start_time'
37/2.new.01<class 'opentimelineio.schema.clip.Clip'> Clip.media_reference.available_range.duration.rate does not exist, 'NoneType' object has no attribute 'duration'
37/2.new.01<class 'opentimelineio.schema.clip.Clip'> Clip.media_reference.available_range.start_time.rate does not exist, 'NoneType' object has no attribute 'start_time'
37/2.new.01<class 'opentimelineio.schema.clip.Clip'> Clip.media_reference.available_range.duration.rate does not exist, 'NoneType' object has no attribute 'duration'
37/2.new.01<class 'opentimelineio.schema.clip.Clip'> Clip.media_reference.available_range.start_time.rate does not exist, 'NoneType' object has no attribute 'start_time'`

**Comment by ssteinbach** [comment]
Some kind of media reference is definitely needed at the moment, but I'd need to take a look at the AAF you're trying to round trip to understand better.  Would you be able to share a test file with us?

Thanks!

**Comment by timlehr** [comment]
No follow up with an example. Let's close this one for now. If it is still an issue, please file a new issue over at https://github.com/OpenTimelineIO/otio-aaf-adapter
