### ISSUE TITLE
Kdenlive adapter fails on opening dissolve

### ISSUE THREAD

**Issue by vpinon** [AcademySoftwareFoundation/OpenTimelineIO#797]
## Bug Report

- [ ] Build Problem
- [x] Incorrect functionality
- [] General question

Describe the bug here. If it is a build issue, please note whether the issue was encountered via `cmake`, `pip`, or `tox`.

Bug studied and fixed in coming PR

## To Reproduce

1. Operating System: Linux (Debian testing)
2. Python version: 3.8
3. Example snippet that demonstrates the issue: from contrib/opentimelineio_contrib/adapters/tests/sample_data
otioconvert -i kdenlive_example.kdenlive -o kdenlive_example.otio
4. OpenTimelineIO release version or commit hash: 22e2468b32f75e8e8ec8d542accba92435dcbd16
5. Compiler information: gcc version 10.2.0

## Expected Behavior

otioconvert kdenlive adapter shouldn't fail on files with opening dissolves

## Screenshots

N/A

## Logs

Traceback (most recent call last):
  File "/home/vpinon/.local/bin/otioconvert", line 33, in <module>
    sys.exit(load_entry_point('OpenTimelineIO==0.14.0.dev1', 'console_scripts', 'otioconvert')())
  File "/home/vpinon/.local/lib/python3.8/site-packages/opentimelineio/console/otioconvert.py", line 226, in main
    result_tl = otio.adapters.read_from_file(
  File "/home/vpinon/.local/lib/python3.8/site-packages/opentimelineio/adapters/__init__.py", line 140, in read_from_file
    return adapter.read_from_file(
  File "/home/vpinon/.local/lib/python3.8/site-packages/opentimelineio/adapters/adapter.py", line 131, in read_from_file
    result = self._execute_function(
  File "/home/vpinon/.local/lib/python3.8/site-packages/opentimelineio/plugins/python_plugin.py", line 174, in _execute_function
    return (getattr(self.module(), func_name)(**kwargs))
  File "/home/vpinon/.local/lib/python3.8/site-packages/opentimelineio_contrib/adapters/kdenlive.py", line 145, in read_from_string
    in_offset=time(transition.get('in'), rate),
  File "/home/vpinon/.local/lib/python3.8/site-packages/opentimelineio_contrib/adapters/kdenlive.py", line 44, in time
    hms = [float(x) for x in clock.replace(',', '.').split(':')]
AttributeError: 'NoneType' object has no attribute 'replace'

**Comment by vpinon** [comment]
PR: #798

**Comment by jminor** [comment]
Closing this since the Kdenlive adapter has been moved elsewhere: https://github.com/AcademySoftwareFoundation/OpenTimelineIO/pull/1438
